# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabbed_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(902, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabTiedot = QtGui.QWidget()
        self.tabTiedot.setObjectName(_fromUtf8("tabTiedot"))
        self.widget = QtGui.QWidget(self.tabTiedot)
        self.widget.setGeometry(QtCore.QRect(30, 70, 168, 154))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widget1 = QtGui.QWidget(self.tabTiedot)
        self.widget1.setGeometry(QtCore.QRect(270, 30, 131, 194))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_6 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_2.addWidget(self.lineEdit_6, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.widget1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_2.addWidget(self.lineEdit_3, 3, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_2.addWidget(self.lineEdit_4, 4, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_2.addWidget(self.lineEdit_5, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tabTiedot, _fromUtf8(""))
        self.tabLonkka = QtGui.QWidget()
        self.tabLonkka.setObjectName(_fromUtf8("tabLonkka"))
        self.tabWidget.addTab(self.tabLonkka, _fromUtf8(""))
        self.tabPolvi = QtGui.QWidget()
        self.tabPolvi.setObjectName(_fromUtf8("tabPolvi"))
        self.tabWidget.addTab(self.tabPolvi, _fromUtf8(""))
        self.tabVirheAs = QtGui.QWidget()
        self.tabVirheAs.setObjectName(_fromUtf8("tabVirheAs"))
        self.tabWidget.addTab(self.tabVirheAs, _fromUtf8(""))
        self.tabNilkka = QtGui.QWidget()
        self.tabNilkka.setObjectName(_fromUtf8("tabNilkka"))
        self.tabWidget.addTab(self.tabNilkka, _fromUtf8(""))
        self.tabAntrop = QtGui.QWidget()
        self.tabAntrop.setObjectName(_fromUtf8("tabAntrop"))
        self.tabWidget.addTab(self.tabAntrop, _fromUtf8(""))
        self.tabJalkat = QtGui.QWidget()
        self.tabJalkat.setObjectName(_fromUtf8("tabJalkat"))
        self.tabWidget.addTab(self.tabJalkat, _fromUtf8(""))
        self.tabSpast = QtGui.QWidget()
        self.tabSpast.setObjectName(_fromUtf8("tabSpast"))
        self.tabWidget.addTab(self.tabSpast, _fromUtf8(""))
        self.tabTasap = QtGui.QWidget()
        self.tabTasap.setObjectName(_fromUtf8("tabTasap"))
        self.tabWidget.addTab(self.tabTasap, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.btnTallenna = QtGui.QPushButton(self.centralwidget)
        self.btnTallenna.setObjectName(_fromUtf8("btnTallenna"))
        self.verticalLayout.addWidget(self.btnTallenna)
        self.btnTallennaLom = QtGui.QPushButton(self.centralwidget)
        self.btnTallennaLom.setObjectName(_fromUtf8("btnTallennaLom"))
        self.verticalLayout.addWidget(self.btnTallennaLom)
        self.btnSulje = QtGui.QPushButton(self.centralwidget)
        self.btnSulje.setObjectName(_fromUtf8("btnSulje"))
        self.verticalLayout.addWidget(self.btnSulje)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Liikeradat", None))
        self.label_2.setText(_translate("MainWindow", "Potilaskoodi", None))
        self.label_4.setText(_translate("MainWindow", "Henkilötunnus", None))
        self.label_3.setText(_translate("MainWindow", "Potilaan nimi", None))
        self.label_5.setText(_translate("MainWindow", "Diagnoosi", None))
        self.label_6.setText(_translate("MainWindow", "Mittaajat", None))
        self.label.setText(_translate("MainWindow", "Tutkimuksen päivämäärä", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTiedot), _translate("MainWindow", "Potilaan tiedot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLonkka), _translate("MainWindow", "Lonkka", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPolvi), _translate("MainWindow", "Polvi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVirheAs), _translate("MainWindow", "Virheasennot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNilkka), _translate("MainWindow", "Nilkka", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAntrop), _translate("MainWindow", "Antrop. mitat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabJalkat), _translate("MainWindow", "Jalkaterän asento", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpast), _translate("MainWindow", "Spastisiteetti", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTasap), _translate("MainWindow", "Tasapaino", None))
        self.btnTallenna.setText(_translate("MainWindow", "Tallenna raportti", None))
        self.btnTallennaLom.setText(_translate("MainWindow", "Tallenna lomake", None))
        self.btnSulje.setText(_translate("MainWindow", "Sulje", None))

